### ISSUE TITLE
Override default webpack configuration

### ISSUE THREAD

**Issue by izziaraffaele** [Glorian/laravel-elixir-webpack-advanced#4]
I would like to be able to customize the entire set of configuration options passed to webpack. Right now I'm able to only merge my custom configurations so I cannot disable plugins or loaders which I don't want to use.

Maybe instead of use `mergeWith` here https://github.com/Glorian/laravel-elixir-webpack-advanced/blob/master/index.js#L47 you should use `assign` and use an empty object as first parameter ( this will enable to run the `mix.webpack()` multiple times with different configurations )

**Comment by Glorian** [comment]
Well, I'll think about it. Thanks for requesting.

**Comment by fedeisas** [comment]
This is useful for setting the `webpack_config.devtool` as well.

**Comment by sanex3339** [comment]
+1
