### ISSUE TITLE
3.5 release gulp issue (GulpPaths)

### ISSUE THREAD

**Issue by grandelc** [Glorian/laravel-elixir-webpack-advanced#7]
I just updated to 3.5 and I'm having issues running my gulp task. I get a syntax error 'Unexpected Token {' on line 24 in the index.js file.

```
{GulpPaths, versionPath} = require('./lib/GulpPaths'),
^
```

**Comment by Glorian** [comment]
Write your version of node, please.

**Comment by grandelc** [comment]
Node version: 5.10.0
Gulp: 3.9.1

**Comment by Glorian** [comment]
Hm.. It seems that node 5.\* doesn't support es6 destructuring.
Quick fix (for now): upgrade node to 6.*
Soon I'll fix that for older node version.

**Comment by Glorian** [comment]
Closed in v0.3.7
